### ISSUE TITLE
Doesn't work with Linux kernels compiled with the "ipddp" module

### ISSUE THREAD

**Issue by aseering** [zero2sixd/macipgw#3]
Linux has an existing "ipddp" module that appears to be intended to implement some subset of the functionality of this program.  When the "ipddp" module is built, even as a module that's not loaded, all DDP packets of protocol type 22 (DDPTYPE_MACIP) get redirected in the kernel into code that's intended to handle ipddp packets.  (This happens [here](https://github.com/torvalds/linux/blob/master/net/appletalk/ddp.c#L1281).)  As a result, those packets never reach the macipgw application, so are not handled by it.

I don't know that macipgw itself can do much about this.  But it is a limitation.  Likely workaround (I haven't tested) is to recompile the kernel with both CONFIG_IPDDP and CONFIG_IPDDP_MODULE disabled.

**Comment by jasonking3** [comment]
Sorry, yes, ipddp needs to be disabled when the AppleTalk module is built, otherwise the kernel will eat the ipddp packets.  I have been meaning to update the readme with that little tidbit.

**Comment by jasonking3** [comment]
I saw the same thing as you when I looked at the appletalk kernel module code.  It automatically eats type 22 DDP packets when IPDDP is enabled and does so in a very static fashion (i.e. no way to turn it off at runtime).  This came up when I was helping the A2SERVER maintainers integrate macipgw with their code base.  They run a generic debian kernel that has IPDDP enabled by default.  I didn't see it in the original porting work because I was using Raspbian and it wasn't enabled in the appletalk module I was using.

Anyway, I am going to close this issue since the requirement to disable IPDDP is now in the README and there is nothing to be done within the macipgw code base to fix it.  We can re-open it later if something changes.

(One thought I had was to go after the macgated implementation as well since it uses the built-in IPDDP functionality of Linux.  I think somewhere I found a relatively recent working version but I didn't bookmark it.  However, my motivation to do that is pretty low since macipgw is working fine.)
